// Code generated by protoc-gen-go. DO NOT EDIT.
// source: city.proto

package city

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CityQuery struct {
	Citycode             string   `protobuf:"bytes,1,opt,name=citycode,proto3" json:"citycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CityQuery) Reset()         { *m = CityQuery{} }
func (m *CityQuery) String() string { return proto.CompactTextString(m) }
func (*CityQuery) ProtoMessage()    {}
func (*CityQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{0}
}

func (m *CityQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CityQuery.Unmarshal(m, b)
}
func (m *CityQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CityQuery.Marshal(b, m, deterministic)
}
func (m *CityQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CityQuery.Merge(m, src)
}
func (m *CityQuery) XXX_Size() int {
	return xxx_messageInfo_CityQuery.Size(m)
}
func (m *CityQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_CityQuery.DiscardUnknown(m)
}

var xxx_messageInfo_CityQuery proto.InternalMessageInfo

func (m *CityQuery) GetCitycode() string {
	if m != nil {
		return m.Citycode
	}
	return ""
}

type Citys struct {
	Citys                []*City  `protobuf:"bytes,1,rep,name=Citys,proto3" json:"Citys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Citys) Reset()         { *m = Citys{} }
func (m *Citys) String() string { return proto.CompactTextString(m) }
func (*Citys) ProtoMessage()    {}
func (*Citys) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{1}
}

func (m *Citys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Citys.Unmarshal(m, b)
}
func (m *Citys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Citys.Marshal(b, m, deterministic)
}
func (m *Citys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Citys.Merge(m, src)
}
func (m *Citys) XXX_Size() int {
	return xxx_messageInfo_Citys.Size(m)
}
func (m *Citys) XXX_DiscardUnknown() {
	xxx_messageInfo_Citys.DiscardUnknown(m)
}

var xxx_messageInfo_Citys proto.InternalMessageInfo

func (m *Citys) GetCitys() []*City {
	if m != nil {
		return m.Citys
	}
	return nil
}

// The request message containing the user's name.
type City struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Citycode             string   `protobuf:"bytes,2,opt,name=citycode,proto3" json:"citycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *City) Reset()         { *m = City{} }
func (m *City) String() string { return proto.CompactTextString(m) }
func (*City) ProtoMessage()    {}
func (*City) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{2}
}

func (m *City) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_City.Unmarshal(m, b)
}
func (m *City) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_City.Marshal(b, m, deterministic)
}
func (m *City) XXX_Merge(src proto.Message) {
	xxx_messageInfo_City.Merge(m, src)
}
func (m *City) XXX_Size() int {
	return xxx_messageInfo_City.Size(m)
}
func (m *City) XXX_DiscardUnknown() {
	xxx_messageInfo_City.DiscardUnknown(m)
}

var xxx_messageInfo_City proto.InternalMessageInfo

func (m *City) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *City) GetCitycode() string {
	if m != nil {
		return m.Citycode
	}
	return ""
}

type AreaQuery struct {
	Citycode             string   `protobuf:"bytes,1,opt,name=citycode,proto3" json:"citycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AreaQuery) Reset()         { *m = AreaQuery{} }
func (m *AreaQuery) String() string { return proto.CompactTextString(m) }
func (*AreaQuery) ProtoMessage()    {}
func (*AreaQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{3}
}

func (m *AreaQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AreaQuery.Unmarshal(m, b)
}
func (m *AreaQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AreaQuery.Marshal(b, m, deterministic)
}
func (m *AreaQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AreaQuery.Merge(m, src)
}
func (m *AreaQuery) XXX_Size() int {
	return xxx_messageInfo_AreaQuery.Size(m)
}
func (m *AreaQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_AreaQuery.DiscardUnknown(m)
}

var xxx_messageInfo_AreaQuery proto.InternalMessageInfo

func (m *AreaQuery) GetCitycode() string {
	if m != nil {
		return m.Citycode
	}
	return ""
}

type Areas struct {
	Areas                []*Area  `protobuf:"bytes,1,rep,name=Areas,proto3" json:"Areas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Areas) Reset()         { *m = Areas{} }
func (m *Areas) String() string { return proto.CompactTextString(m) }
func (*Areas) ProtoMessage()    {}
func (*Areas) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{4}
}

func (m *Areas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Areas.Unmarshal(m, b)
}
func (m *Areas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Areas.Marshal(b, m, deterministic)
}
func (m *Areas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Areas.Merge(m, src)
}
func (m *Areas) XXX_Size() int {
	return xxx_messageInfo_Areas.Size(m)
}
func (m *Areas) XXX_DiscardUnknown() {
	xxx_messageInfo_Areas.DiscardUnknown(m)
}

var xxx_messageInfo_Areas proto.InternalMessageInfo

func (m *Areas) GetAreas() []*Area {
	if m != nil {
		return m.Areas
	}
	return nil
}

type Area struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Citycode             string   `protobuf:"bytes,2,opt,name=citycode,proto3" json:"citycode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_f63625ed15d5bd67, []int{5}
}

func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (m *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(m, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Area) GetCitycode() string {
	if m != nil {
		return m.Citycode
	}
	return ""
}

func init() {
	proto.RegisterType((*CityQuery)(nil), "city.CityQuery")
	proto.RegisterType((*Citys)(nil), "city.Citys")
	proto.RegisterType((*City)(nil), "city.City")
	proto.RegisterType((*AreaQuery)(nil), "city.AreaQuery")
	proto.RegisterType((*Areas)(nil), "city.Areas")
	proto.RegisterType((*Area)(nil), "city.Area")
}

func init() { proto.RegisterFile("city.proto", fileDescriptor_f63625ed15d5bd67) }

var fileDescriptor_f63625ed15d5bd67 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x31, 0x0f, 0x82, 0x30,
	0x14, 0x84, 0x41, 0xd1, 0xc0, 0x63, 0x30, 0xe9, 0x44, 0x98, 0x48, 0x17, 0xd0, 0x81, 0x01, 0x13,
	0x77, 0xe3, 0xaa, 0x83, 0xfc, 0x83, 0x8a, 0x8d, 0x61, 0x10, 0x4c, 0xa9, 0x03, 0xff, 0xde, 0x5c,
	0x11, 0x10, 0x27, 0xdd, 0xae, 0xf7, 0x2e, 0xef, 0x7d, 0x97, 0x12, 0x15, 0xa5, 0x6e, 0xd3, 0x87,
	0xaa, 0x75, 0xcd, 0x1c, 0x68, 0x1e, 0x93, 0x77, 0x28, 0x75, 0x7b, 0x7e, 0x4a, 0xd5, 0xb2, 0x90,
	0x5c, 0x98, 0x45, 0x7d, 0x95, 0x81, 0x1d, 0xd9, 0x89, 0x97, 0x0f, 0x6f, 0xbe, 0xa6, 0x05, 0x82,
	0x0d, 0x8b, 0xde, 0x22, 0xb0, 0xa3, 0x79, 0xe2, 0x67, 0x94, 0x9a, 0x9d, 0xb0, 0xf2, 0x6e, 0xc0,
	0x77, 0xe4, 0x40, 0x30, 0x46, 0x4e, 0x25, 0xee, 0xfd, 0x2a, 0xa3, 0x27, 0x27, 0x66, 0x5f, 0x27,
	0x62, 0xf2, 0xf6, 0x4a, 0x8a, 0x9f, 0x58, 0x10, 0x34, 0x2c, 0x46, 0x4c, 0x59, 0x60, 0xe5, 0xdd,
	0x00, 0x2c, 0x10, 0xff, 0xb2, 0x64, 0x92, 0x7c, 0x74, 0x38, 0x89, 0x4a, 0xdc, 0xa4, 0x62, 0x1b,
	0x72, 0xf1, 0x3c, 0x96, 0x8d, 0x66, 0xab, 0xb1, 0xb1, 0x41, 0x0d, 0xfd, 0xd1, 0x68, 0xb8, 0x85,
	0x2c, 0x4e, 0x7e, 0x66, 0x87, 0x5a, 0x7d, 0xb6, 0x83, 0xb3, 0x2e, 0x4b, 0xf3, 0x17, 0xdb, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x72, 0x7b, 0xbe, 0x99, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CityManagerClient is the client API for CityManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CityManagerClient interface {
	// get city list
	CityList(ctx context.Context, in *CityQuery, opts ...grpc.CallOption) (*Citys, error)
	AreaList(ctx context.Context, in *AreaQuery, opts ...grpc.CallOption) (*Areas, error)
}

type cityManagerClient struct {
	cc *grpc.ClientConn
}

func NewCityManagerClient(cc *grpc.ClientConn) CityManagerClient {
	return &cityManagerClient{cc}
}

func (c *cityManagerClient) CityList(ctx context.Context, in *CityQuery, opts ...grpc.CallOption) (*Citys, error) {
	out := new(Citys)
	err := c.cc.Invoke(ctx, "/city.CityManager/CityList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cityManagerClient) AreaList(ctx context.Context, in *AreaQuery, opts ...grpc.CallOption) (*Areas, error) {
	out := new(Areas)
	err := c.cc.Invoke(ctx, "/city.CityManager/AreaList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CityManagerServer is the server API for CityManager service.
type CityManagerServer interface {
	// get city list
	CityList(context.Context, *CityQuery) (*Citys, error)
	AreaList(context.Context, *AreaQuery) (*Areas, error)
}

// UnimplementedCityManagerServer can be embedded to have forward compatible implementations.
type UnimplementedCityManagerServer struct {
}

func (*UnimplementedCityManagerServer) CityList(ctx context.Context, req *CityQuery) (*Citys, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CityList not implemented")
}
func (*UnimplementedCityManagerServer) AreaList(ctx context.Context, req *AreaQuery) (*Areas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AreaList not implemented")
}

func RegisterCityManagerServer(s *grpc.Server, srv CityManagerServer) {
	s.RegisterService(&_CityManager_serviceDesc, srv)
}

func _CityManager_CityList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CityQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityManagerServer).CityList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityManager/CityList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityManagerServer).CityList(ctx, req.(*CityQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CityManager_AreaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AreaQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CityManagerServer).AreaList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/city.CityManager/AreaList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CityManagerServer).AreaList(ctx, req.(*AreaQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _CityManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "city.CityManager",
	HandlerType: (*CityManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CityList",
			Handler:    _CityManager_CityList_Handler,
		},
		{
			MethodName: "AreaList",
			Handler:    _CityManager_AreaList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "city.proto",
}
